---
minimum_pre_commit_version: "3.0.0"

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: mixed-line-ending
          args: [--fix=lf]
        - id: check-merge-conflict
        - id: check-added-large-files
        - id: check-yaml
        - id: check-toml

    - repo: local
      hooks:
        - id: fmt
          name: cargo fmt
          entry: cargo fmt --all --
          language: system
          types: [rust]
          pass_filenames: false

        - id: clippy
          name: cargo clippy
          entry: cargo clippy --all-targets --all-features -- -D warnings
          language: system
          types: [rust]
          pass_filenames: false

        - id: opengrep
          name: opengrep
          entry: opengrep scan --config auto --error --quiet
          language: system
          types: [rust]
          pass_filenames: false

        - id: zizmor
          name: zizmor
          entry: zizmor --offline
          language: system
          files: ^\.github/workflows/.*\.ya?ml$
